### ISSUE TITLE
Add run mode where HTML file is generated but no email is sent

### ISSUE THREAD

**Issue by nathan-weinberg** [nathan-weinberg/jeeves#114]
Currently the `--save` flag saves an HTML file of the report being sent over email. However at present there is no way to save this file without sending an email. We want to extend and maybe even do a slight refactor of the Jeeves CLI to make this an option.

**Comment by nathan-weinberg** [comment]
A refactored approach could look as follows:

- Deprecate `--save`, `--test`, and `--remind` flags
- Introduce new flag, `--mode` with following valid args:
    - `save`: Jeeves sends email **and** saves to archive
    - `save-only`: Jeeves **only** saves to archive, does not send mail
    - `test`: Jeeves sends email to `email_to_test` address and **does not** save report
    - `remind`: Jeeves runs in reminder mode and **does not** save 
- Not using `--mode` would lead to default behavior of only sending email to `email_to` address
- Invalid arg to `--mode` exits program

**Comment by gouthampacha** [comment]
Hi Nathan, 

This looks like a worthy improvement, however, I seek to simplify a bit:

I don't see a reason to send without saving. So saving any normal report (not a reminder) can become the default. What do you think? With this simplification, the "mode" will only need:

* `save-only`: Jeeves skips sending the email, just archives the report generated
* `test`: Jeeves sends an email to the `email_to_test` address
* `remind`: Jeeves runs in reminder mode and does not `save`

WDYT?

**Comment by nathan-weinberg** [comment]
@gouthampacha I like the suggestion, going to let others contribute as well and mull it over

**Comment by amodi5** [comment]
> Hi Nathan,
> 
> This looks like a worthy improvement, however, I seek to simplify a bit:
> 
> I don't see a reason to send without saving. So saving any normal report (not a reminder) can become the default. What do you think? With this simplification, the "mode" will only need:
> 
> * `save-only`: Jeeves skips sending the email, just archives the report generated
> * `test`: Jeeves sends an email to the `email_to_test` address
> * `remind`: Jeeves runs in reminder mode and does not `save`
> 
> WDYT?

Agree +1

**Comment by nathan-weinberg** [comment]
Agree but one minor tweak - I feel `test` should not save a report because that would basically be the same thing as running `save-only` but also sending to the test email

**Comment by nathan-weinberg** [comment]
Opening a PR for this - discussion can continue there

**Comment by itzikb** [comment]
@nathan-weinberg 

When running with--no-email I get:
```
Error loading configuration data:  field "email_subject" is not defined
```
I expect not to check for email configuration when running with --no-email

What do you think?

**Comment by nathan-weinberg** [comment]
@itzikb Sounds like a bug, would you mind opening an issue for it and I can take a look at it sometime this week?

In the meantime, try defining an "email_subject" field in your config file with an empty value and see if that works as a workaround

**Comment by itzikb** [comment]
An empty value doesn't work, an empty string works
