### ISSUE TITLE
Adding gerrit links to blocker_files

### ISSUE THREAD

**Issue by pavankrao** [nathan-weinberg/jeeves#132]
Recently, on of my CI job build failed and I had to reference the blockers file with a gerrit patch. Can we add a feature to reference gerrit link to the blocker_files

Thank you

**Comment by EliadCohen** [comment]
Hi @pavankrao 
I think maybe the "other" field can help you accomplish this?
See: https://github.com/nathan-weinberg/jeeves/blob/master/blockers.yaml.example#L29

Or did I miss the requirement?

**Comment by nathan-weinberg** [comment]
Eliad is right - the 'other' field covers this usecase. Please see the example blocker file for how to implement.
