### ISSUE TITLE
"No blocker" annotations are not very helpful when some blockers exist

### ISSUE THREAD

**Issue by gouthampacha** [nathan-weinberg/jeeves#140]
This is an opinion rather than a bug. I feel we could make reporting compact by not emitting extra rows for bugzillas/tickets/others if there aren't any. For example, here's a job that has no bugzillas or tickets, but has a blocker annotation:

![Screenshot 2020-07-22 09 30 15](https://user-images.githubusercontent.com/6268206/88202682-16a0f380-cbfe-11ea-980b-0f80044f7472.png)

It would be better if we could represent it like this:

![Screenshot 2020-07-22 09 33 02](https://user-images.githubusercontent.com/6268206/88202938-6a134180-cbfe-11ea-824e-1a4221a7e868.png)

When we have a failing job that has no blockers of any kind defined, we could call that out in a single line:

_"No blockers have been filed for this job"_

**Comment by nathan-weinberg** [comment]
As part of the RFE, we should have blocker fields be present for ABORTED and MISSING jobs
