### ISSUE TITLE
Omit Bugs,Tickets and Other fields in Blockers column when there is no data 

### ISSUE THREAD

**Issue by itzikb** [nathan-weinberg/jeeves#144]
It's an Opinion rather than an issue.
It will be great to omit the mentioned fields from the report when there is not data , e.g. when no there are no bugs there is no point to have the Bugs field

**Comment by nathan-weinberg** [comment]
@itzikb This seems very similar to #140 

Would you agree or can you cite any differences?

**Comment by itzikb** [comment]
duplicate of #140
