### ISSUE TITLE
Build selection criteria for should be configurable and the default changed

### ISSUE THREAD

**Issue by tosky** [nathan-weinberg/jeeves#158]
The criteria for selecting which builds should be picked for reporting are fixed, and 
- the current ones are not useful anymore for the original purposes of jeeves (for which only jobs with a certain label should be selected)
- changing the default to match the current reality may fix things for a while, but it would be better to make them configurable and set per-project.

**Comment by nathan-weinberg** [comment]
So, there are several ways we could implement this. My first thought would be adding a section to `config.yaml` where users could specify tags in Jenkins (e.g. 'PUBLISH_TO_POLARION') that Jeeves would use by fetching the last completed build with the specified tags.

@itzikb @amodi5 @AlistairTonner Please share your thoughts as this change would affect your DFGs as well
