### ISSUE TITLE
Enhance report visualization with doughnutpie charts

### ISSUE THREAD

**Issue by pavankrao** [nathan-weinberg/jeeves#162]
I would like to show a comparison below:

Current visualization with pie chart:
![old compute](https://user-images.githubusercontent.com/46899831/93224751-75d33e00-f73f-11ea-8dc1-0f6887742dc1.png)

Proposed visualization with doughnutpie chart:
![new compute](https://user-images.githubusercontent.com/46899831/93224798-8388c380-f73f-11ea-84de-cb8b83fac436.png)

This proposal improves numbers readablity against each category of jobs and also adds the total job count in the centre.

**Comment by amodi5** [comment]
Isn't "aborted" grey in Jenkins?

**Comment by pavankrao** [comment]
> Isn't "aborted" grey in Jenkins?

I have updated the colors based on the below commit.
https://github.com/nathan-weinberg/jeeves/pull/161/commits/65f6ad2f85f5d594fd5c9487695999a61d92f23a

**Comment by nathan-weinberg** [comment]
Yes, "aborted" shows as black whereas "not run" shows as gray
