### ISSUE TITLE
Make supported versions a configurable field

### ISSUE THREAD

**Issue by nathan-weinberg** [nathan-weinberg/jeeves#168]
Right now OSP supported versions is hardcoded value - it may make more sense to have this as an configurable value in `config.yaml`

**Comment by amodi5** [comment]
Why so? Does anyone want to publish non-supported release jobs?

**Comment by tosky** [comment]
> Why so? Does anyone want to publish non-supported release jobs?

That doesn't matter. Configuration should be always outside the code whenever possible.

**Comment by amodi5** [comment]
> > Why so? Does anyone want to publish non-supported release jobs?
> 
> That doesn't matter. Configuration should be always outside the code whenever possible.

Well, I agree, but in this case we can enforce the list of supported releases

**Comment by agarcia64** [comment]
I believe that having the supported versions enforced across all DFG reports is more important than any stylistic improvements that would come from moving the supported versions to the config.yaml. Personally I don't see myself using this new field and I believe that (worst case scenario) this may lead to situations where DFGs unintentionally report on unsupported versions.

**Comment by nathan-weinberg** [comment]
While I still think this is a feature worth having, I'm going to set this to low priority for now since it is not pressing
