### ISSUE TITLE
Provide a way for users to add text/body on top of the generated report 

### ISSUE THREAD

**Issue by amodi5** [nathan-weinberg/jeeves#169]
Currently, we can send the report with the job fields and the chart. To make it more customized and fit the needs of users, we want to have a way to provide additional text, for example- some sort of summary, on top of the report.

I'm not sure how this can be done in a more user friendly way, but let me know if anyone has suggestions. Do u think there is a better solution than having a yaml/text file to put the contents in?

**Comment by joehakimrahme** [comment]
YAML supports multiline strings, so I would vote for adding a field in the yaml called "description" or "weekly_summary"

**Comment by nathan-weinberg** [comment]
I like the idea - I agree the simplest but perhaps not the most-user friendly way of doing this would be defining in a separate file, either as part of the existing config YAML or maybe by passing an HTML file as command line arg, which could be injected in the report jinja2 template?

**Comment by EliadCohen** [comment]
Aside from it's name, the blockers file seems like a good place to introduce a description. This also scales well when using jeeves_config
+1 on the idea

**Comment by agarcia64** [comment]
+1 on this
I agree with adding a field in the blockers yaml file to keep jeeves streamlined. Usability should be prioritized if we want more DFGs to adopt jeeves as their reporting tool.

**Comment by AlistairTonner** [comment]
Absolutely would like having a place to drop in a "summary"/"Commentary" about the report.  I think it would be better in a standalone file (of any format) that could be included, and updated separately from blockers.  Perhaps an option would be to have *either* "string field" containing the comment or *pointer* to a URI for the data in blockers-${dfg}.yaml?
   If we decide to go with the pointer, the URI could  point to blockers_files/${dfg}_commentary.${ext} or some other path in the repo.....

**Comment by amodi5** [comment]
I'm fine with having both the options available to the user, any suggestions on implementation? Should it be a bulleted list with custom levels of indentation (for sub-list points), should it be tabular,  how can we make the user customization as friendly as possible

**Comment by nathan-weinberg** [comment]
> I'm fine with having both the options available to the user, any suggestions on the implementation? Should it be a bulleted list with custom levels of indentation (for sub-list points), should it be tabular, how can we make the user customization as friendly as possible

I think a raw HTML injection would allow the greatest level of flexibility - since the email is already a jinja2 template this would be trivial to implement. The question I think that remains is where do we want this custom (and optional) HTML preface to live - the blocker file, the config file, or a separate file altogether?

Once we decide on that we can begin implementation

**Comment by amodi5** [comment]
> > I'm fine with having both the options available to the user, any suggestions on the implementation? Should it be a bulleted list with custom levels of indentation (for sub-list points), should it be tabular, how can we make the user customization as friendly as possible
> 
> I think a raw HTML injection would allow the greatest level of flexibility - since the email is already a jinja2 template this would be trivial to implement. The question I think that remains is where do we want this custom (and optional) HTML preface to live - the blocker file, the config file, or a separate file altogether?
i think we can rule out config file completely, since this doesn't look anything config related.
> 
> Once we decide on that we can begin implementation

**Comment by pbabbar3** [comment]
I think most of my concerns are already addressed here and I do think having a separate summary file will make sense and we should not be overlapping with config files here.

we can give flexibility to the user to customize the file the way he wants like adding bullets/numeric or the way he want to use the indentation and then append that file and render it in the email beginning. This will be very trivial solution and then may be later we can standardized things in summary. I mean whichever way is quicker we should go for that!:)

**Comment by nathan-weinberg** [comment]
/polls "Summary in blockers file" "Summary in seperate file"

**Comment by nathan-weinberg** [comment]
/polls 'Summary in blockers file' "Summary in separate file"

**Comment by pavankrao** [comment]
+1
