### ISSUE TITLE
Does jeeves really need to login to jenkins?

### ISSUE THREAD

**Issue by odyssey4me** [nathan-weinberg/jeeves#178]
It would appear from my brief review of https://python-jenkins.readthedocs.io/en/latest/api.html#jenkins.Jenkins that python-jenkins allows anonymous access to jenkins.

Given that jeeves is only reading data out of jenkins about job states, surely it does not actually need to login?

The use of a login user and API token adds an unnecessary complexity and also creates some risk. It'd be better if we could avoid all of that if possible.

**Comment by nathan-weinberg** [comment]
@odyssey4me You are welcome to investigate this - IIFC authenticating with Jenkins is required, but that portion of the code was implemented over a year ago so I don't remember exactly what happens if you don't. If it turns out we don't need to auth, great.

**Comment by nathan-weinberg** [comment]
@odyssey4me I take it by the opening of this PR you've found that Jenkins credentials are not required?

**Comment by odyssey4me** [comment]
> @odyssey4me I take it by the opening of this PR you've found that Jenkins credentials are not required?

Yep, works for me. The only reason it's required is to get the user email address. The PR as it stands should maintain current functionality.

**Comment by nathan-weinberg** [comment]
> > @odyssey4me I take it by the opening of this PR you've found that Jenkins credentials are not required?
> 
> Yep, works for me. The only reason it's required is to get the user email address. The PR as it stands should maintain current functionality.

Very interesting find, thanks for looking into this!

I'm wondering now if it may be worth simply removing the Jenkins authentication for users entirely, if it serves no purpose apart from providing an email address.

@agarcia64 @amodi5 @EliadCohen @jamepark4 @pavankrao @pbabbar3 Would love to hear y'alls thoughts on this

**Comment by odyssey4me** [comment]
> I'm wondering now if it may be worth simply removing the Jenkins authentication for users entirely, if it serves no purpose apart from providing an email address.

Sure, although there should be a transition period anyway to allow anyone who's using this to change their config.

**Comment by nathan-weinberg** [comment]
Given the issues we've had with tokens recently (my token has been nuked twice over the last few days due to the Jenkins resets) I think there is some real value in removing these kinds of requirements entirely

**Comment by odyssey4me** [comment]
> Given the issues we've had with tokens recently (my token has been nuked twice over the last few days due to the Jenkins resets) I think there is some real value in removing these kinds of requirements entirely

Fair point. Let's see what the feedback from others is. I'm happy either way.

**Comment by jamepark4** [comment]
Trying this commit with Nova's weekly reports did not yield any problems or issues.  I am definitely ok with switching over to the removal of the api tokens, especially since we would need to regenerate the tokens again in the near future.

**Comment by agarcia64** [comment]
I support completely removing the authentication, +1

**Comment by nathan-weinberg** [comment]
At this point I'm willing to call it - let's remove Jenkins auth entirely. @odyssey4me Do you think you could retool #180 to remove Jenkins auth altogether?

**Comment by odyssey4me** [comment]
Yep, will do that today.

**Comment by odyssey4me** [comment]
Done!
