### ISSUE TITLE
Add a new "mode" flag to run Jeeves in report, remind, or another mode

### ISSUE THREAD

**Issue by nathan-weinberg** [nathan-weinberg/jeeves#191]
Replace `--remind` flag with `--mode` flag with the following behavior:
- `--mode` has two arguments, `report` and `remind`
- Default mode is `report`
- Example usage: `./jeeves.py --mode remind`
- Could be easily extended to allow for other run modes

**Comment by nathan-weinberg** [comment]
@odyssey4me Was brainstorming of ways to help align upstream Jeeves with Upgrade DFG's needs - thinking we could introduce a run mode for publishing to Confluence by creating a new file in the `jeeves/` subdirectory called `confluence.py` or something like that. Then it's a simple logic switch in the root `jeeves.py` file to run the `confluence.py` code which can be tailored to your DFG's needs. Thoughts?

**Comment by odyssey4me** [comment]
@nathan-weinberg I was kinda hoping to use https://github.com/proctorlabs/confluence-cli instead of carrying our own code for uploading to confluence. It would just need working out the CI bit to use a container to upload the artifact.

I haven't really had the chance to look into how to change gitlab to make that happen just yet.

**Comment by nathan-weinberg** [comment]
@odyssey4me Sounds good, I may go ahead and make the change (I figure this general approach will allow for any DFG to have the option to make a run mode if they have custom needs in the future) but feel free to implement whatever is needed to fit your usecase.

**Comment by nathan-weinberg** [comment]
@odyssey4me This may interest you as well: https://atlassian-python-api.readthedocs.io/confluence.html#page-actions
