### ISSUE TITLE
Add a column to see the latest failing stage

### ISSUE THREAD

**Issue by itzikb** [nathan-weinberg/jeeves#195]
It can be useful to see at which stage a job failed at for example to see if couple of jobs failed at the same stage.

**Comment by nathan-weinberg** [comment]
@odyssey4me @ciecierski @jamepark4 You've all implemented something similar to this at one point, correct?

**Comment by jamepark4** [comment]
Excert(s) below of identifying stage failure that I run when gathering all latest job results and aggregating based on build/tempest failures.  The 'fail_url' api endpoint has a stages dictionary in the return value that lists the name and result of each stage executed, along with some other bits of information.

fail_url = '{}/job/{}/{}/wfapi/describe'.format(JENK_URL,url,build_no)
build_failures = await fetch(session, fail_url)
stages = build_failures['stages']
for stage in stages:
    if stage['status'] == 'FAILED':
        stage_failed = stage.get('name', 'Unknown')

**Comment by ciecierski** [comment]
@nathan-weinberg @itzikb yes, we have it implemented. Take a look at https://github.com/sathlan/jeeves/commit/dc215d06c9947842d4be91d5620647d0c6952d73
I wanted to create separate pr with this code, but @itzikb feel free to do it if you want.

**Comment by itzikb** [comment]
@ciecierski If you already implemented it there is no reason to create another PR, just assign it to yourself please.

**Comment by nathan-weinberg** [comment]
@ciecierski One request - if you make the column, can you put it between "Result" and "Failed Tempest Tests" ?

with an "N/A" value for "SUCCESS", "ABORTED", and "NO_KNOWN_BUILDS" jobs
