### ISSUE TITLE
Minimize bugzilla api calls by passing a list of unique bug numbers

### ISSUE THREAD

**Issue by EliadCohenRH** [nathan-weinberg/jeeves#20]
Currently the api calls https://github.com/nathan-weinberg/jeeves/blob/master/main.py#L37-L66 iterate through a list of bugs from all job blockers which includes non-uniques potentially.

Change the function call to pass a list of uniques list(set(bugs)) and also append the bug number as a key:
`bugs.append(
  {
        bug_id:[
	    'bug_name': bug_name, 
	    'bug_url': bug_url
            ]
  }`

**Comment by nathan-weinberg** [comment]
As part of this enhancement it would be great if we could eliminate the need for the `all_bugs` and `all_tickets` variables to be part of global scope.

Currently they are declared globally but used by function calls without being explicitly passed back and forth; the latter is messy and the former is generally considered bad practice.

If some sort of pre-processing is to be done prior to the `get_bugzilla()` and `get_jira()` function calls, perhaps the logic currently present in those functions (specifically `all_bugs.append(bug_id)` and `all_tickets.append(ticket_id)` respectively) could be moved into the main thread of execution and solve this scope issue.
