### ISSUE TITLE
Fix sorting logic so jobs are always ordered by descending OSP version in HTML table

### ISSUE THREAD

**Issue by nathan-weinberg** [nathan-weinberg/jeeves#21]

**Comment by nathan-weinberg** [comment]
Notes on current implementation:

Once all jenkins jobs are fetched and filtered, the main loop of iteration processes them as so:

`for job in jobs[::-1]`

This is done so that jobs are processed starting with OSP16 and descending down the versions in the set, building the rows for the report in said order. However this implementation does not always work as we have seen with EST jobs.

**Comment by nathan-weinberg** [comment]
Recommendation for fix:

Once all rows have been assembled the easiest way to ensure they are sorted correctly prior to building the report would be a descending sort based off `osp_version` key/value pair. Following this implementation the main loop of iteration can and should be changed to the following:

`for job in jobs`

as the order in which the jobs are processed will no longer matter.

**Comment by nathan-weinberg** [comment]
@jngrosso Please also test this using multiple 'job_search_fields' entries; specifically 'DFG-ceph-rhos,DFG-all-unified'

**Comment by jngrosso** [comment]
@nathan-weinberg  acknowledged
