### ISSUE TITLE
codecov check fails due to PR #243 "Move test requirements."

### ISSUE THREAD

**Issue by agarcia64** [nathan-weinberg/jeeves#244]
The error message when codecov is run is:
'Process completed with exit code 127.'

**Comment by agarcia64** [comment]
@damani42 Could you please assign yourself to this issue and submit a fix when you can?

**Comment by damani42** [comment]
Ok I will do that.

**Comment by damani42** [comment]
I can't assign me the issue sorry, can you assign to me please?
