### ISSUE TITLE
Report reflects blocker totals/uniques in blocker file, not actual report

### ISSUE THREAD

**Issue by nathan-weinberg** [nathan-weinberg/jeeves#47]
The report summary will always show the total/unique blockers in the **blocker file**, not what is actually in the report. E.g. if you have a blocker file for ceph jobs and sent a report for unified jobs, even though the report will state "Could not find relevant bug/ticket" for every non-successful job, the summary will still show what is in the blocker file.

**Comment by nathan-weinberg** [comment]
Looks like the summary issues are larger than I initially thought; going to try and fix them all before sending out the report this Friday.

**Comment by EliadCohen** [comment]
You can change the name of the item on the report to "*Known* blocker totals/uniques" no?
@nathan-weinberg

**Comment by nathan-weinberg** [comment]
@EliadCohen I could, but I want the summary to reflect what is visible in the report; not what is present in the config files. Next step following this is determining why there emerged a discrepancy in the first place :)
