### ISSUE TITLE
Modularize bugzilla calls

### ISSUE THREAD

**Issue by EliadCohen** [nathan-weinberg/jeeves#53]
Create a bugzilla connector class:

* Allow multiple ids queried in one call.
* Generate a dictionary to return to the main program
* automatically include the [0] proposition for no bug on file
* Remember to dispose of api objects when done

Some references here:
https://github.com/python-bugzilla/python-bugzilla/blob/master/examples/query.py

**Comment by nathan-weinberg** [comment]
Low-priority for now; I want to do a full modularization effort as part of 2.0
