### ISSUE TITLE
Allow using a search filter in the form of a regex

### ISSUE THREAD

**Issue by EliadCohen** [nathan-weinberg/jeeves#55]
Jenkins' search field doesn't allow the use or a regular expression to search. 
However - it could be nice if we could pass a regex to filter the search results and thus narrow the report

**Comment by nathan-weinberg** [comment]
@EliadCohen Specifically you are talking about passing a regex to `job_search_fields` correct?

**Comment by EliadCohen** [comment]
> @EliadCohen Specifically you are talking about passing a regex to `job_search_fields` correct?

To `job_search_fields` or if easier to an alternative field `job_search_fields_regex`
But the idea is the same, yes

**Comment by nathan-weinberg** [comment]
The best way to do this is probably in `get_jenkins_jobs`, specifically here:

```python
# parse list of search fields
fields = job_search_fields.split(',')
fields_length = len(fields)

# remove spacing from strings
for i in range(fields_length):
	fields[i] = fields[i].strip(' ')

# fetch all jobs from server
all_jobs = server.get_jobs()
```

If users are using regular job_search_fields i.e. how it's done now, the logic is fine. If they want to use a regex, we should a) identify a way to determine if they're doing that b) skip the splitting and simply use the `re` library to see what job names in `all_jobs` match the regex, and return that list

**Comment by nathan-weinberg** [comment]
@EliadCohen Could you add a link here to that function you found in the python-jenkins docs?

**Comment by EliadCohen** [comment]
@nathan-weinberg 
Here it is: https://python-jenkins.readthedocs.io/en/latest/api.html#jenkins.Jenkins.get_job_info_regex

**Comment by nathan-weinberg** [comment]
Thanks @EliadCohen 

@jngrosso @agarcia64 see above ^^
