### ISSUE TITLE
search fields break when a space follows a comma

### ISSUE THREAD

**Issue by EliadCohen** [nathan-weinberg/jeeves#59]
if config.yaml contains fields separated by a ', ' (space following a comma) the filtering may fail.
Can be fixed by adding :
```python
	for i in range(0,len(fields)):
		fields[i] = fields[i].lstrip()
```
to get_jenkins_jobs

**Comment by nathan-weinberg** [comment]
Please declare
```python
fields_length = len(fields)
```
outside the loop as a local variable and then use it as so
```python
range(fields_length)
```

This avoids have _n_ additional function calls

**Comment by nathan-weinberg** [comment]
Removing the "bug" label b/c docs explain proper usage, but this would still be a great feature to have.

@jngrosso Do you think you could get a PR in for this this week?

**Comment by nathan-weinberg** [comment]
@jngrosso, @agarcia64 is going to help out with this as well
