### ISSUE TITLE
Move towards pep8 (start with tabs->spaces)

### ISSUE THREAD

**Issue by tosky** [nathan-weinberg/jeeves#61]
"Spaces are the preferred indentation method."

**Comment by nathan-weinberg** [comment]
See comments in #62

**Comment by damani42** [comment]
Can I ask you why you want use tabs instead spaces?

**Comment by nathan-weinberg** [comment]
@damani42 I prefer tabs - I'll point out this decision was made several years ago, there are more productive things that can be done with the project than rehashing this.

**Comment by damani42** [comment]
@nathan-weinberg, it was only a question. I mean all python projects use spaces, it was not for rehashing.
