### ISSUE TITLE
Add try/except handling for Jira client

### ISSUE THREAD

**Issue by EliadCohen** [nathan-weinberg/jeeves#81]
https://github.com/nathan-weinberg/jeeves/blob/1ff945b346c0295e72e7abd3cfa3fd6fc8a3d74d/main.py#L97

Explicitly:
`jira = JIRA(auth=auth, options=options)` should be wrapped by try/except

**Comment by nathan-weinberg** [comment]
@EliadCohen Isn't this handled later on in the function? in functions.py

```python
# get ticket info from jira API
try:
	issue = jira.issue(ticket_id)
	ticket_name = issue.fields.summary
except Exception as e:
	print("Jira API Call Error: ", e)
	ticket_name = ticket_id
finally:
	ticket_url = config['jira_url'] + "/browse/" + str(ticket_id)
	tickets[ticket_id] = {
		'ticket_name': ticket_name,
		'ticket_url': ticket_url
	}
```

**Comment by EliadCohen** [comment]
@nathan-weinberg Initializing the client with wrong config may cause an exception.
If the following block picks up erroneous details, the client initialization fails with an unhandled exception.
```python
auth = (config['jira_username'], config['jira_password'])
options = {
		"server": config['jira_url'],
		"verify": config['certificate']
	}
```

**Comment by nathan-weinberg** [comment]
@EliadCohen Do we know if failing connection initialization throws an exception?

python-jenkins, for example, does not as far as I know - you have to make try and make a call via the connection first to get any kind of exception raised

**Comment by EliadCohen** [comment]
@nathan-weinberg  I did
MissingSchema if you mess up the url
OSError when you mess up the cert

Anything you do to auth will throw things into an infinite recursion resulting in a RecursionError (Runtime error)
