### ISSUE TITLE
Make --remind a bit more generic 

### ISSUE THREAD

**Issue by gouthampacha** [nathan-weinberg/jeeves#82]
Pull #80 added the functionality to use jeeves in a "--remind" mode. It currently reminds any tagged owners of a change that does not have any blocker on it (one of bugzilla, jira, others). Jenkins Jobs may be failing due to multiple reasons - there's already a provision for this in jeeves, because all the trackers accept lists, so a single job can have one or more blocking BZs, jiras or other notes. 

Currently, for a job that fails because of multiple reasons, having just one existing blocker can turn off the reminder and this may not be desirable. I'd like "--remind" to always send a reminder when invoked - and allow owners to make the decision to update the blockers or not.

Conversation on Pull #80 - https://github.com/nathan-weinberg/jeeves/pull/80#discussion_r414163893

**Comment by nathan-weinberg** [comment]
What if we refactored the reminder feature as so:
- Reminder consists of all jobs where owner is marked as responsible
- Add a new column "Triaged Status" or something of the like to the far right side of the reminder
- Use existing `has_blockers()` function to mark job "Triaged" or "Untriaged" in new column

**Comment by gouthampacha** [comment]
> What if we refactored the reminder feature as so:
> 
> * Reminder consists of all jobs where owner is marked as responsible
> * Add a new column "Triaged Status" or something of the like to the far right side of the reminder
> * Use existing `has_blockers()` function to mark job "Triaged" or "Untriaged" in new column

So will a human/owner update this column?

**Comment by nathan-weinberg** [comment]
> > What if we refactored the reminder feature as so:
> > 
> > * Reminder consists of all jobs where owner is marked as responsible
> > * Add a new column "Triaged Status" or something of the like to the far right side of the reminder
> > * Use existing `has_blockers()` function to mark job "Triaged" or "Untriaged" in new column
> 
> So will a human/owner update this column?

Nope, the column would be updated automatically as so:
- If a job is "PASSED" or in some sort of error state (i.e. "NO_KNOWN_BUILDS", "ERROR") mark cell as "N/A"
- If a job is "UNSTABLE" or "FAILED" and has blockers already logged, mark as "Triaged" (maybe with a reminder to update any blockers that may be stale)
- If a job is "UNSTABLE" or "FAILED" and has no blockers logged, mark cell as "Untriaged"

**Comment by nathan-weinberg** [comment]
@amodi5 @EliadCohen Do either of you have any thoughts on this?

**Comment by EliadCohen** [comment]
@nathan-weinberg You are saying that the job will be in the table even though it has a blocker(s) on file right?
Will you link the blocker list?
I like the idea of multiple ownership and different causes, I also think we need to balance reminders with user accountability

**Comment by nathan-weinberg** [comment]
> @nathan-weinberg You are saying that the job will be in the table even though it has a blocker(s) on file right?
Yes
> Will you link the blocker list?
No - at that point we're just sending out a report with an extra column :)
> I like the idea of multiple ownership and different causes, I also think we need to balance reminders with user accountability
Right, this should maintain that

**Comment by gouthampacha** [comment]
We expect this reminder feature to be used sparingly, correct? In our current use case, it is triggered once a week.

It makes sense to include the existing blockers in the email, and add text at the top of the email calling out that the jobs owned by the recipient are failing, and may have blockers that may be out of date. These blockers must be updated if they indeed are out of date. 

If the blockers are provided, ``Triaged  Status`` doesn't add any further value...

**Comment by EliadCohen** [comment]
We are starting to see how stale blockers may be an issue, think we should prioritize this

**Comment by nathan-weinberg** [comment]
@gouthampacha @EliadCohen How about this - reminder sends a "mini-report" of **only** UNSTABLE and FAILED jobs, with a bit at the top with something along the lines of "these jobs are failing CI, please ensure all blockers are up to date" etc. etc.

Basically the same functionality as now, but removing the `has_blockers()` requirement. The function will remain in `functions.py` in case we want it for future use` or if we want to still use if via an additional command line arg or something of the like

**Comment by gouthampacha** [comment]
+1, agree

**Comment by EliadCohen** [comment]
I like it too +1
