### ISSUE TITLE
Add logging for email sending to ensure successful send

### ISSUE THREAD

**Issue by nathan-weinberg** [nathan-weinberg/jeeves#84]
SMTP protocol allows 48 hours for email delivery; we need to ensure emails will be successful delivered from a programmatic standpoint so we don't rely on instant delivery w/ manual confirmation that a report or reminder was successfully delivered

Ref: https://www.socketlabs.com/blog/21-smtp-response-codes-that-you-need-to-know

**Comment by nathan-weinberg** [comment]
According to https://docs.python.org/3/library/smtplib.html#smtplib.SMTP.sendmail (docs for the function being used to send all Jeeves mail) an exception should be thrown if the server is expected to not successfully deliver the mail to at least one recipient

>This method will return normally if the mail is accepted for at least one recipient. Otherwise it will raise an exception. That is, if this method does not raise an exception, then someone should get your mail. If this method does not raise an exception, it returns a dictionary, with one entry for each recipient that was refused. Each entry contains a tuple of the SMTP error code and the accompanying error message sent by the server.

As such, we should expect an empty dictionary returned from our `sendmail` function. Otherwise an exception should be raised, saving the report to archive (if it isn't already to do so via `--save`)

**Comment by gouthampacha** [comment]
What's the specific error code you hit?

**Comment by nathan-weinberg** [comment]
@gouthampacha Didn't hit an error code, but at present the logging to determine if one has been hit (or not hit) is not there - as such I was unaware earlier today if messages were being successfully sent or not. I'm going to put a PR to try and handle this early next week.

**Comment by gouthampacha** [comment]
Ah, I see.. Thank you, I thought we're hitting an exception. Logging makes sense - if jeeves has been automated as a cron job, you can push these log messages to the cron owner..
